#!/bin/sh

echo "Creating user and group bigclown..."

addgroup --quiet --system bigclown || true
adduser --quiet --system \
	--home /dev/null \
	--no-create-home \
	--ingroup bigclown \
	bigclown || true
